review fixes

diff --git a/.github/workflows/check_licenses.yml b/.github/workflows/check_licenses.yml
--- a/.github/workflows/check_licenses.yml
+++ b/.github/workflows/check_licenses.yml
@@ -2,7 +2,7 @@ name: Check and update licenses
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "main", "licenses" ]
   pull_request:
     branches:  [ "main", "licenses" ]
         #    types: [opened, synchronized]
@@ -132,22 +132,31 @@ jobs:
                 module load Python-bundle-PyPI/2023.06-GCCcore-12.3.0
                 module load BeautifulSoup/4.12.2-GCCcore-12.3.0
                 module load PyYAML/6.0-GCCcore-12.3.0
-                python licenses/parse_licenses.py --debug modules_results.json
-                cat licenses_test.yaml
+                python licenses/parse_licenses.py modules_results.json
+                cat licenses_aux.yaml
               else
                 echo "modules_results.json file does not exist, skipping license fetch."
               fi
               
-      - name: Check for missing licenses
+      - name: Check and generate report on missing licenses
         run: |
-              grep -3 "not found" licenses_test.yaml 
-              exit_code=$?
-              if [[ ${exit_code} -ne 0 ]]; then 
-                echo "No missing licenses found."
+              echo ""
+              # Look for missing licences in licenses_aux.yaml
+              OUTPUT=$(yq eval '.. | select(has("License")) | select(.License == "not found" or .License == "Other") | (path | join(" --> ")) + ": " + .License' licenses_aux.yaml)
+              
+              # Check if the variable is NOT empty (-n)
+              if [[ -n "$OUTPUT" ]]; then
+                echo "Missing licenses found, please check the missing_report.yaml file."
+                echo "$OUTPUT"
+                echo "$OUTPUT" > missing_report.yaml
               else
-                echo "Missing licenses found, please check the licenses.json file."
-                #exit 1
+                echo "No missing licenses found."
               fi
+
+              # Create a patch file
+              python licenses/reformat_yaml.py licenses/licenses.yaml    #Reformat licenses.yaml to match the structure of licenses_aux.yaml
+              diff -Naur reformatted_licenses.yaml licenses_aux.yaml > patch.txt || true
+              echo -e "\npatch.txt file generated."
 
 
       - name: Generate artifacts
@@ -155,18 +164,16 @@ jobs:
         with:
           name: license-results-${{ matrix.NO_SLASH_NAME }}
           path: |
-            licenses_test.yaml
-            modules_results.json
-            missing_modules.txt
+            missing_report.yaml
+            patch.txt
 
 
       - name: How to edit artifacts
         run: |
-              echo "Artifacts generated. To resolve the missing licenses, please edit 'licenses_test.yaml' manually, making sure you follow the following format: "
+              echo "Artifacts generated. To resolve the missing licenses, please edit 'patch.txt' manually, making sure you follow the following format: "
               echo ""
               echo "<package_name>:"
               echo "  <version_id>:"
               echo "    License: <license_info>"
               echo "    Permission to redistribute: <true/false>"
               echo "    Retrieved from: <source_link>"
-
