rookie mistake

diff --git a/.github/workflows/check_licenses.yml b/.github/workflows/check_licenses.yml
--- a/.github/workflows/check_licenses.yml
+++ b/.github/workflows/check_licenses.yml
@@ -55,10 +55,8 @@ jobs:
               echo "exit code for eb --missing --easystack ${easystack_file} is ${exit_code}"
               grep " required modules missing:" ${eb_missing_out} # > /dev/null
               exit_code=$?
-              echo "debugging exit code for grep is ${exit_code}"
-              cat ${eb_missing_out}
               
-              if [[ ${exit_code} -ne 0 ]]; then echo "missing installations found for ${easystack_file}!" >&2;
+              if [[ ${exit_code} -eq 0 ]]; then echo "missing installations found for ${easystack_file}!" >&2;
               else
                 echo "no missing installations found for ${easystack_file}."
                 exit 0
