also test create_lmodsitepackage.py in CI

diff --git a/.github/workflows/tests_scripts.yml b/.github/workflows/tests_scripts.yml
--- a/.github/workflows/tests_scripts.yml
+++ b/.github/workflows/tests_scripts.yml
@@ -5,6 +5,7 @@ on:
     paths:
       - build_container.sh
       - create_directory_tarballs.sh
+      - create_lmodsitepackage.py
       - EESSI-install-software.sh
       - install_software_layer.sh
       - load_easybuild_module.sh
@@ -16,6 +17,7 @@ on:
     paths:
       - build_container.sh
       - create_directory_tarballs.sh
+      - create_lmodsitepackage.py
       - EESSI-install-software.sh
       - install_software_layer.sh
       - load_easybuild_module.sh
@@ -94,3 +96,22 @@ jobs:
           ./eessi_container.sh --mode run --verbose /software-layer/create_directory_tarballs.sh 2023.06
           # check if tarballs have been produced
           ls -l *.tar.gz
+
+    - name: test create_lmodsitepackage.py script
+      run: |
+          # bind current directory into container as /software-layer
+          export SINGULARITY_BIND="${PWD}:/software-layer"
+
+          python3 create_lmodsitepackage.py .
+          export LMOD_PACKAGE_PATH="$PWD/.lmod"
+          # run some commands to make sure that generated Lmod SitePackage file works
+          test_script="${PWD}/test_lmod_sitepackage.sh"
+          echo '#!/bin/bash' > ${test_script}
+          echo 'ml --config' >> ${test_script}
+
+          chmod u+x ${test_script}
+
+          ./eessi_container.sh --mode run --verbose /software-layer/run_in_compat_layer_env.sh /software-layer/test_lmod_sitepackage.sh 2>&1 | tee ${out}
+          for pattern in "^Site Pkg location.*$PWD/.lmod/SitePackage.lua" "LMOD_SITEPACKAGE_LOCATION.*${PWD}/.lmod/SitePackage.lua"; do
+            grep "${pattern}" ${out} || (echo "Pattern '${pattern}' not found in output!" && exit 1)
+          done
