Add check to see if we need forced CI

diff --git a/.github/workflows/test-software.eessi.io.yml b/.github/workflows/test-software.eessi.io.yml
--- a/.github/workflows/test-software.eessi.io.yml
+++ b/.github/workflows/test-software.eessi.io.yml
@@ -146,7 +146,26 @@ jobs:
           echo "EESSI_VERSIONS<<EOF" >> "$GITHUB_OUTPUT"
           echo "$EESSI_VERSIONS" >> "$GITHUB_OUTPUT"
           echo "EOF" >> "$GITHUB_OUTPUT"
+          
+  requires_forced_ci:
+    runs-on: ubuntu-24.04
+    needs: check_EESSI_version_changed_files
+    steps:
+      - name: Check whether force-ci-checks is required
+        if: >
+          needs.check_EESSI_version_changed_files.outputs.EESSI_VERSIONS == ''
+          && !contains(github.event.pull_request.labels.*.name, 'force-ci-checks')
+        run: |
+          echo "::error::No EasyStack changes detected, so missing-installation CI was skipped."
+          echo "::error::If this PR still requires missing-installation CI, someone with triage rights needs to add the 'force-ci-checks' label."
+          exit 1
 
+      - name: Force CI label is present or EasyStack changes detected
+        if: >
+          needs.check_EESSI_version_changed_files.outputs.EESSI_VERSIONS != ''
+          || contains(github.event.pull_request.labels.*.name, 'force-ci-checks')
+        run: echo "No forced CI required."
+    
   check_missing:
     if: >
       (
