flesh out load_easybuild_module.sh script from EESSI-pilot-install-software.sh

diff --git a/.github/workflows/tests_scripts.yml b/.github/workflows/tests_scripts.yml
--- a/.github/workflows/tests_scripts.yml
+++ b/.github/workflows/tests_scripts.yml
@@ -4,22 +4,26 @@ on:
   push:
     paths:
       - build_container.sh
+      - create_directory_tarballs.sh
+      - EESSI-pilot-install-software.sh
       - install_software_layer.sh
+      - load_easybuild_module.sh
       - run_in_compat_layer_env.sh
       - scripts/utils.sh
       - update_lmod_cache.sh
-      - create_directory_tarballs.sh
 
   pull_request:
     branches:
       - main
     paths:
       - build_container.sh
+      - create_directory_tarballs.sh
+      - EESSI-pilot-install-software.sh
       - install_software_layer.sh
+      - load_easybuild_module.sh
       - run_in_compat_layer_env.sh
       - scripts/utils.sh
       - update_lmod_cache.sh
-      - create_directory_tarballs.sh
 permissions:
   contents: read # to fetch code (actions/checkout)
 jobs:
@@ -32,6 +36,48 @@ jobs:
     - name: install Apptainer
       run: |
         ./install_apptainer_ubuntu.sh
+
+    - name: test load_easybuild_module.sh script
+      run: |
+        export TMPDIR=$(mktemp -d)
+
+        # run tests from /tmp where scripts were copied into,
+        # since scripts must be accessible from within build container
+        cp -a * /tmp/
+        cd /tmp
+
+        for EB_VERSION in '4.5.0' '4.5.1' '4.7.2'; do
+          # Create script that uses load_easybuild_module.sh which we can run in compat layer environment
+          # note: Be careful with single vs double quotes below!
+          #       ${TMPDIR} and ${EB_VERSION} should be expanded, so use double quotes;
+          #       For statements using variables that are only defined in the script, like ${EASYBUILD_INSTALLPATH},
+          #       use single quotes to avoid expansion while creating the script.
+          test_script="${TMPDIR}/eb-${EB_VERSION}.sh"
+          echo '#!/bin/bash' > ${test_script}
+          # both $EB and $TMPDIR environment must be set, required by load_easybuild_module.sh script
+          echo 'export EB="eb"' >> ${test_script}
+          echo "export TMPDIR=${TMPDIR}" >> ${test_script}
+          # set up environment to have utility functions in place that load_easybuild_module.sh script relies on,
+          # along with $EESSI_* environment variables, and Lmod
+          echo 'source /tmp/scripts/utils.sh' >> ${test_script}
+          echo 'source /tmp/init/eessi_environment_variables' >> ${test_script}
+          echo 'source ${EPREFIX}/usr/share/Lmod/init/bash' >> ${test_script}
+          # minimal configuration for EasyBuild so we can test installation aspect of load_easybuild_module.sh script
+          echo "export EASYBUILD_INSTALLPATH=${TMPDIR}" >> ${test_script}
+          echo 'module use ${EASYBUILD_INSTALLPATH}/modules/all' >> ${test_script}
+          echo '' >> ${test_script}
+          echo "source /tmp/load_easybuild_module.sh ${EB_VERSION}" >> ${test_script}
+          echo 'module list' >> ${test_script}
+          echo 'eb --version' >> ${test_script}
+
+          chmod u+x ${test_script}
+
+          # run wrapper script + capture & check output
+          out="${TMPDIR}/eb-${EB_VERSION}.out"
+          ./build_container.sh run /tmp/$USER/EESSI /tmp/run_in_compat_layer_env.sh ${test_script} 2>&1 | tee ${out}
+          pattern="^This is EasyBuild ${EB_VERSION} "
+          grep "${pattern}" ${out} || (echo "Pattern '${pattern}' not found in output!" && exit 1)
+        done
 
     - name: test install_software_layer.sh script
       run: |
