separated test cases + updated evaluation of test result

diff --git a/.github/workflows/test_eessi.yml b/.github/workflows/test_eessi.yml
--- a/.github/workflows/test_eessi.yml
+++ b/.github/workflows/test_eessi.yml
@@ -42,11 +42,26 @@ jobs:
               env | grep ^EESSI | sort
               echo "just run check_missing_installations.sh (should use eessi-${{matrix.EESSI_VERSION}}.yml)"
               ./check_missing_installations.sh
+
+        - name: Test check_missing_installations.sh with missing package
+          run: |
+              source /cvmfs/pilot.eessi-hpc.org/versions/${{matrix.EESSI_VERSION}}/init/bash
+              module load EasyBuild
+              eb --version
+              export EESSI_PREFIX=/cvmfs/pilot.eessi-hpc.org/versions/${{matrix.EESSI_VERSION}}
+              export EESSI_OS_TYPE=linux
+              export EESSI_SOFTWARE_SUBDIR=${{matrix.EESSI_SOFTWARE_SUBDIR}}
+              env | grep ^EESSI | sort
               echo "modify eessi-${{matrix.EESSI_VERSION}}.yml by adding a missing package"
               echo "  GCC:" >> eessi-${{matrix.EESSI_VERSION}}.yml
               echo "    toolchains:" >> eessi-${{matrix.EESSI_VERSION}}.yml
               echo "      SYSTEM:" >> eessi-${{matrix.EESSI_VERSION}}.yml
               echo "        versions: '8.3.0'" >> eessi-${{matrix.EESSI_VERSION}}.yml
               tail -n 8 eessi-${{matrix.EESSI_VERSION}}.yml
-              ./check_missing_installations.sh
-              [[ $? -eq 0 ]] && exit 1 || exit 0
+              if ./check_missing_installations.sh; then
+                echo "captured missing package; test PASSED"
+                exit 0
+              else
+                echo "did NOT capture missing package; test FAILED"
+                exit 1
+              fi
